language: python
python:
-   '2.7'
-   '3.4'
-   '3.5'
-   '3.6'
before_install:
- chmod +x ci/run_tests.sh
install:
- travis_retry pip install --upgrade pip
- travis_retry pip install tox

script:
-   ./ci/run_tests.sh